version: '3.9'
services:
  app:
    build: .
    image: food4thought:latest
    container_name: food4thought
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - EMAIL_HOST=${EMAIL_HOST:-}
      - EMAIL_PORT=${EMAIL_PORT:-}
      - EMAIL_USER=${EMAIL_USER:-}
      - EMAIL_PASS=${EMAIL_PASS:-}
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./public:/app/public:ro
    restart: unless-stopped
